create TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    name varchar,
    CONSTRAINT uq_email UNIQUE(email)
);

create TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar NOT NULL,
    owner_id INTEGER REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    created TIMESTAMP
);

create TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar NOT NULL,
    available boolean NOT NULL,
    owner_id INTEGER REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    request_id INTEGER REFERENCES requests (id) ON delete CASCADE ON update CASCADE
);

create TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    item_id INTEGER REFERENCES items (id) ON delete CASCADE ON update CASCADE,
    booker_id INTEGER REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    status varchar(10) NOT NULL
);

create TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar NOT NULL,
    item_id INTEGER REFERENCES items (id) ON delete CASCADE ON update CASCADE,
    author_id INTEGER REFERENCES users (id) ON delete CASCADE ON update CASCADE,
    created TIMESTAMP
);